---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service  # Label of the service
    app: demo-voting-app
  namespace: prod  # Namespace for the pod

spec:
  selector:  # Selector to match pods with specific labels
    name: postgres-pod # Label of the pod
    app: demo-voting-app
  ports:
    - port: 5432  # Service port
      targetPort: 5432  # Pod's container port
  type: ClusterIP  # Service type