---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service  # Label of the service
    app: demo-voting-app
  namespace: prod  # Namespace for the pod

spec:
  selector:  # Selector to match pods with specific labels
    name: redis-pod # Label of the pod
    app: demo-voting-app
  ports:
    - port: 6379  # Service port
      targetPort: 6379  # Pod's container port
  type: ClusterIP  # Service type