---
apiVersion: v1
kind: Service
metadata:
  name: voting-service 
  labels:
    name: voting-service  # Label of the service
    app: demo-voting-app
  namespace: prod  # Namespace for the pod

spec:
  selector:  # Selector to match pods with specific labels
    name: voting-app-pod  # Label of the pod
    app: demo-voting-app
  ports:
    - port: 80  # Service port
      targetPort: 80  # Pod's container port
      nodePort: 30004  # Node port for external access
  type: NodePort  # Service type