---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: prod
  labels:
    name: postgres-deployment
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: job
                operator: In
                values:
                - db
      containers:
        - name: postgres
          image: postgres
          ports:
          - containerPort: 5432
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 400Mi
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - pg_isready
              - -U
              - postgres
            initialDelaySeconds: 15
            periodSeconds: 20
          envFrom:
            - secretRef:
                name: db-secret