---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: prod  # Namespace for the service
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
      name: postgres-pod
      app: demo-voting-app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  # Pod's container port
  type: ClusterIP  # Service type