---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: prod  # Namespace for the service
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  selector:
      name: redis-pod
      app: demo-voting-app
  ports:
    - port: 6379  # Service port
      targetPort: 6379  # Pod's container port
  type: ClusterIP  # Service type