---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: prod
spec:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 4Gi
    limits.cpu: "2"
    limits.memory: 6Gi