---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: prod  # Namespace for the service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  selector:
        name: result-app-pod
        app: demo-voting-app # Selector for the pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005  # Node port for external access
  type: NodePort  # Service type