---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  namespace: prod
  labels:
    name: result-app-deployment
    app: demo-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app  
  template:
    metadata:
      labels:
        name: result-app-pod
        app: demo-voting-app 
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: job
                operator: In
                values:
                - app
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1  # Image of the container
          ports:
          - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 400Mi
          readinessProbe:  # Readiness probe for the container
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20